### PR TITLE
kindyn updated with proper gymgoal service

### PR DESCRIPTION
**Pull request by BarisYazici**
kindyn updated with random GymGoal service. 
To add the changed in kindyn to DeepAndReinforced I needed first add them under CARDSflow then I comitted the changes in CARDSFlow. After I added the changes in CARDSflow to main git repo. 
So it goes like this->

- First add the changes to kindyn and commit.
-> Push to kindyn
- Add the changes in CARDSflow and commit.
-> Push to CARDSflow
- Add the changes in DeepAndReinforce and commit
-> PUSH everything here

### CODE REVIEW

**Comment by ALPA-Industry-and-Technology** [comment]
Unfortunately, the `git submodule update --init --recursive` command is not working
[Picture](https://picload.org/view/dciiaild/baris.png.html)

**Review by tomasruizt — CHANGES_REQUESTED** [review]
It throws that error when cloning from scratch.
```bash
git clone git@github.com:Roboy/DeepAndReinforced.git  
cd DeepAndReinforced/  
git checkout baris-dev  
git submodule update --init --recursive
```

**Review by ALPA-Industry-and-Technology — CHANGES_REQUESTED** [review]
Unfortunately, the `git submodule update --init --recursive` command is not working

baris

**Comment by BarisYazici** [comment]
Ok. It works now. The problem was that I committed the changes but I didn't push in the submodules. So at the moment kindyn and robots submodules are in branch deepRoboy-feature. CARDSflow is already in deepRoboy-feature. 

**I still coudn't fix the detached head problem**

Therefore you need to checkout to deepRoboy-feature of a specific repo if you want to commit anything.

**Pull request merged**
